apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trip-service
  template:
    metadata:
      labels:
        app: trip-service
    spec:
      containers:
        - name: trip-service
          image: europe-west1-docker.pkg.dev/balmy-elevator-416913/ride-sharing/trip-service
          ports:
            - containerPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: trip-service
spec:
  selector:
    app: trip-service
  ports:
    - port: 9093
      name: grpc
      targetPort: 9093
  type: ClusterIP

