// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: rider.proto

package rider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *RiderRequest) Reset() {
	*x = RiderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RiderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderRequest) ProtoMessage() {}

func (x *RiderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderRequest.ProtoReflect.Descriptor instead.
func (*RiderRequest) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{0}
}

func (x *RiderRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *RiderRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type RiderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RiderIds []string `protobuf:"bytes,1,rep,name=rider_ids,json=riderIds,proto3" json:"rider_ids,omitempty"`
}

func (x *RiderResponse) Reset() {
	*x = RiderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RiderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiderResponse) ProtoMessage() {}

func (x *RiderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiderResponse.ProtoReflect.Descriptor instead.
func (*RiderResponse) Descriptor() ([]byte, []int) {
	return file_rider_proto_rawDescGZIP(), []int{1}
}

func (x *RiderResponse) GetRiderIds() []string {
	if x != nil {
		return x.RiderIds
	}
	return nil
}

var File_rider_proto protoreflect.FileDescriptor

var file_rider_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x72,
	0x69, 0x64, 0x65, 0x72, 0x22, 0x48, 0x0a, 0x0c, 0x52, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x2c,
	0x0a, 0x0d, 0x52, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x69, 0x64, 0x65, 0x72, 0x49, 0x64, 0x73, 0x32, 0x4c, 0x0a, 0x0c,
	0x52, 0x69, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x0f,
	0x47, 0x65, 0x74, 0x4e, 0x65, 0x61, 0x72, 0x62, 0x79, 0x52, 0x69, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x13, 0x2e, 0x72, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x72, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x69, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1a, 0x5a, 0x18, 0x73, 0x68,
	0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x69, 0x64, 0x65, 0x72,
	0x3b, 0x72, 0x69, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rider_proto_rawDescOnce sync.Once
	file_rider_proto_rawDescData = file_rider_proto_rawDesc
)

func file_rider_proto_rawDescGZIP() []byte {
	file_rider_proto_rawDescOnce.Do(func() {
		file_rider_proto_rawDescData = protoimpl.X.CompressGZIP(file_rider_proto_rawDescData)
	})
	return file_rider_proto_rawDescData
}

var file_rider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rider_proto_goTypes = []interface{}{
	(*RiderRequest)(nil),  // 0: rider.RiderRequest
	(*RiderResponse)(nil), // 1: rider.RiderResponse
}
var file_rider_proto_depIdxs = []int32{
	0, // 0: rider.RiderService.GetNearbyRiders:input_type -> rider.RiderRequest
	1, // 1: rider.RiderService.GetNearbyRiders:output_type -> rider.RiderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rider_proto_init() }
func file_rider_proto_init() {
	if File_rider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RiderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RiderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rider_proto_goTypes,
		DependencyIndexes: file_rider_proto_depIdxs,
		MessageInfos:      file_rider_proto_msgTypes,
	}.Build()
	File_rider_proto = out.File
	file_rider_proto_rawDesc = nil
	file_rider_proto_goTypes = nil
	file_rider_proto_depIdxs = nil
}
